version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    # environment:
    #   DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

volumes:
  app-db-data: